name: ci

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:  hadolint/hadolint:latest

    steps:
    - uses: actions/checkout@v2

    - name: Run hadolint
      run: hadolint
        Dockerfile.base
        Dockerfile.docker
        Dockerfile.synapse
        Dockerfile.user

  test:
    runs-on: ubuntu-latest
    needs: ['lint']

    steps:
    - uses: actions/checkout@v2

    - name: Validate docker-compose.yml
      run: docker-compose -f docker-compose.yml config

  # build:
  #   runs-on: ubuntu-latest
  #   needs: ['lint']
  #   env:
  #     repository: tschaffter/${{ github.event.repository.name }}

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build Docker image
  #       run: |
  #         docker build
  #           -f Dockerfile.base
  #           -t tschaffter/${repository}:base .
  #         docker build
  #           -f Dockerfile.user
  #           -t tschaffter/${repository}:user .