name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest

    steps:
    - uses: actions/checkout@v2
    - name: Run hadolint
      run: hadolint
        Dockerfile.base
        Dockerfile.docker
        Dockerfile.synapse
        Dockerfile.user

    - name: Validate docker-compose.yml
      run: docker-compose -f docker-compose.yml config